#!/bin/bash
# create directory listing, with hyperlinks, for Azure-hosted results page (for
# public bucket)

# exit on error
set -e

# setup env
. azure/env

# make temporary file
OFNAME=directory.html
rm -f $OFNAME
touch $OFNAME

# pull file list from server
FILES=$(azure/azcopy list $AZURE_PUBLIC_URL | grep -Po " (.+);")

# make listing
for FILE in $FILES; do
    
    # strip trailing semicolon
    FILE=${FILE::-1}

    # don't list the directory
    if [ "$FILE" == "$OFNAME" ]; then
        continue
    fi

    # add hyperlink to listing
    echo "<a href="$AZURE_PUBLIC_URL/$FILE">$FILE</a><br>" >> $OFNAME
done

# upload file
SKIP_DIRECTORY_UPDATE=1 azure/upload $OFNAME

# clean up
rm $OFNAME
