#!/bin/bash
# download $1 from azure
#
# to download from private repo, set PRIVATE=1, e.g.
#   > PRIVATE=1 azure/download fname

# exit on error
set -e

# check args
if [ $# -ne 1 ]; then
    echo "Usage:"
    echo "  > azure/download fname"
    exit 0
fi

# setup env
. azure/env

# get url and token
if [ -z "$PRIVATE" ]; then
    URL=$AZURE_PUBLIC_URL
    KEY=$AZURE_PUBLIC_KEY
else
    URL=$AZURE_PRIVATE_URL
    KEY=$AZURE_PRIVATE_KEY
fi

# upload to azure
azure/azcopy copy "$URL/$(basename $1)?$KEY" $1 1> /dev/null
