#!/bin/bash
# upload $1 to azure
#
# to upload to private repo, set PRIVATE=1, e.g.
#   > PRIVATE=1 azure/upload fname
#
# if uploaded to public, then the directory listing will be updated (with
# cmd/directry), unless SKIP_DIRECTORY_UPDATE=1, e.g.
#   > SKIP_DIRECTORY_UPDATE=1 azure/upload fname

# exit on error
set -e

# check args
if [ $# -ne 1 ]; then
    echo "Usage:"
    echo "  > azure/upload fname"
    exit 0
fi

# setup env
. azure/env

# get url and token
if [ -z "$PRIVATE" ]; then
    URL=$AZURE_PUBLIC_URL
    KEY=$AZURE_PUBLIC_KEY
else
    URL=$AZURE_PRIVATE_URL
    KEY=$AZURE_PRIVATE_KEY
fi

# upload to azure
azure/azcopy copy "$1" "$URL/$(basename $1)?$KEY" 1> /dev/null

# update directory
if [ -z "$SKIP_DIRECTORY_UPDATE" ] && [ -z "$PRIVATE" ]; then
    azure/directory
fi
