user: {
  email: mike@lakeslegendaries.com,
  tool: org.mfoundation.litmon,
}
mbox_fname: [
  data/dump1.mbox,
  data/dump2.mbox,
]
dbase_fit: {
  first_month: 2013/01,
  final_month: 2017/12,
  suffix: fit,
}
dbase_eval: {
  min_date: 2018/01/01,
  max_date: 2018/01/31,
  dbase_fname: data/dbase_eval.csv,
  log_fname: logs/dbase_eval.log,
}
query: >-
  (english[la] OR hasabstract)
  AND
  (
  biogeront*
  OR "regenerative medicine"
  OR "tissue engineering"
  OR oxystero*
  OR "7-ketocholesterol"
  OR lipofus*
  OR aging
  OR ageing
  OR mitochondri*
  OR lysosom*
  OR intein*
  OR telomer*
  OR longevity
  OR glycation
  OR (aggregat* NOT platelet)
  OR amyloid*
  OR synuclein
  OR ("neurofibrillary tangles")
  OR nft
  OR nfts
  OR ("lewy bodies")
  OR ("inclusion bodies")
  OR autophag*
  OR immunosenescence
  OR (integrase* NOT HIV)
  OR (plasma AND redox)
  )
  AND
  (2007 : 2025[dp])
