#!/bin/bash
# run full pipeline

set -e
python litmon/cli/mbox.py
python litmon/cli/pos.py
python litmon/cli/dbase.py
python litmon/cli/fit.py
python litmon/cli/dbase.py -f user dbase_eval
python litmon/cli/eval.py
python litmon/cli/rez.py
