#!/bin/bash
# this is a test script to get simulated results
# this test uses a model trained 2013-2018,
# and evaluates on each month in 2019-2020
#
# if SKIP_DBASE, then use already-downloaded databases

# download trained model
PRIVATE=1 azure/download data/model-20130101-20181231.bin
PRIVATE=1 azure/download data/model-20130101-20181231.pickle

# run configs
for YEAR in 2019 2020; do
    for MONTH in {1..12}; do

        # get fnames / text strings
        YM_TEXT=$YEAR-$(printf "%02d\n" $MONTH)
        CONFIG=config/$YM_TEXT.yaml

        # make config
        python litmon/utils/config.py \
            -m $MONTH \
            -y $YEAR \
            -s model_fname data/model-20130101-20181231

        # download database
        if [ -z "$SKIP_DBASE" ]; then
            python litmon/cli/dbase.py -c $CONFIG -f \
                user \
                query \
                dbase_eval \
                dbase_fname
        fi

        # score articles
        python litmon/cli/eval.py -c $CONFIG -f \
            dbase_fname \
            model_fname \
            scores_fname

        # write results
        python litmon/cli/rez.py -c $CONFIG -f \
            dbase_fname \
            scores_fname \
            rez_fname

        # upload results to azure
        azure/upload data/$YM_TEXT.xlsx

    done
done
