name: Actions

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: actions
        token: ${{ secrets.GIT_TOKEN }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Install environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
    - name: Make .ezazure file
      env:
        AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
      run: |
        echo "connection_str: $AZURE_TOKEN" > .ezazure
        echo "container: data" >> .ezazure
    - name: Test code
      run: |
        source .venv/bin/activate
        pytest
    - name: Configure git
      run: |
        git config --global user.name "version bot"
        git config --global user.email "<>"
    - name: Increment version, tag branch
      run: |
        OLD_VERSION=$(grep version setup.py | grep -Po "\d+.\d+.\d+")
        NEW_VERSION=$(echo $OLD_VERSION | perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e')
        for file in setup.py docsrc/conf.py litmon/__init__.py; do
            sed s/$OLD_VERSION/$NEW_VERSION/g $file -i
            git add $file
        done
        git commit -m "Release $NEW_VERSION [no ci]"
        git tag $NEW_VERSION
    - name: Update documentation
      run: |
        source .venv/bin/activate
        docsrc/build
    - name: Push to actions
      run: |
        git push origin actions:actions
    - name: Push to main
      run: |
        git push origin actions:main -f
    - name: Push tag
      run: |
        VERSION=$(grep version setup.py | grep -Po "\d+.\d+.\d+")
        git push origin $VERSION
    - name: Publish docs to GitHub pages (docs branch)
      run: |
        git add docs -f
        git commit docs -m "Updating Documentation"
        git push origin actions:docs -f
